disabled_rules: # rule identifiers to exclude from running
- type_name
- identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- SpotifyAppTests
- SpotifyAppUITests
